version: '2'

services:
  influxdb:
    image: influxdb:1.5
    ports:
      - "8083:8083"
      - "8086:8086"
      - "25826:25826/udp"
    volumes:
      - /var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      #For some reasone enviroment variables are not working as intended..
#    environment:
#      PRE_CREATE_DB: "Relativity Space" --  Already made... named collectd
#      INFLUXDB_ADMIN_ENABLED: "true"
#      INFLUXDB_ADMIN_USER = root
#      INFLUXDB_ADMIN_PASSWORD=root
  grafana:
    image: grafana/grafana:3.1.1
    ports:
      - "3000:3000"
    volumes:
      - /var/lib/grafana
  collectd:
    image: fr3nd/collectd
    privileged: true
    network_mode: host
    volumes:
      - /proc:/mnt/proc:ro
      - ./collectd.conf:/etc/collectd/collectd.conf      
      
 #  extra service goes here
 #      image: Twain's image to load data into a CSV file from a publically available CSV
 #      LOAD IN DATA FROM CSV FILE to our influxdb 'Relativity Space' HERE

